### ISSUE TITLE
Jenkins publisher plugin sonar publish step issue

### ISSUE THREAD

**Issue by vbottu** [Hygieia/Hygieia#2913]
Hello,
I generated the sonarpublishbuildstep using pipeline syntax generator and using that in my jenkinsfile to push sonar metrics to hygieia but it fails to do and throws the below error
        ``java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1967)
	at hygieia.builder.SonarBuilder.getSonarMetrics(SonarBuilder.java:192)
	at jenkins.plugins.hygieia.workflow.HygieiaSonarPublishStep$HygieiaSonarPublishStepExecution.run(HygieiaSonarPublishStep.java:123)
	at jenkins.plugins.hygieia.workflow.HygieiaSonarPublishStep$HygieiaSonarPublishStepExecution.run(HygieiaSonarPublishStep.java:81)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:47)
	at hudson.security.ACL.impersonate(ACL.java:290)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by rvema** [comment]
@vbottu What version of the plugin are you using?

**Comment by vbottu** [comment]
2.2.0-SNAPSHOT

**Comment by rvema** [comment]
Can you paste the screenshot of the Hygieia Plugin Settings from Jenkins Global Settings

**Comment by rvema** [comment]
@vbottu can you get the latest code and retry. I believe this issue should be fixed now

**Comment by rvema** [comment]
This issue has been resolved.

**Comment by keir-lavelle** [comment]
Hi there, I am having exactly the same issue with version 2.2.3, is there a more recent version I should be using?

**Comment by keir-lavelle** [comment]
Just tried rebuilding the .hpi from source and adding the plugin again, still the same issue :(  @rvema any chance this issue can be re-opened?

**Comment by rvema** [comment]
@keir-lavelle let me get back to you
