### ISSUE TITLE
CORS issue when api port other than 8080

### ISSUE THREAD

**Issue by bargemb** [Hygieia/Hygieia#2945]
I have UI and API components running on same remote server. UI is served using `gulp serve` as of now.
API is currently running on 8081 port with following configuration
```
dbname=dashboarddb
dbreplicaset=false
dbhostport=localhost:27017
server.contextPath=/api
server.port=8081
logRequest=true
corsEnabled=true
corsWhitelist=http://<IP_ADDRESS>:3000
```
gulpfile.js file content
```
    config = {
        module: 'hygieia-dashboard',
        local: null,
        api: 'http://<IP_ADDRESS>:8081',
        refresh: 60
    };
```
When I click on login button, I get ✅ meaning API connectivity is working properly.
When I try to signup for new user, I get *User already exist* issue. However the actual issue is related to CORS. Here is the screenshot -
![Screen Shot 2019-05-31 at 1 27 01 PM](https://user-images.githubusercontent.com/7900526/58734828-5e870a80-83ad-11e9-9c57-2d95166d2b12.png)
Even if I have added proper whitelisting for CORS configuration */api/registerUser* is not setting proper header *Access-Control-Allow-Origin*
Following are the two screenshots which might help

1. Initial */registerUser* request with OPTIONS
![Screen Shot 2019-05-31 at 1 34 09 PM](https://user-images.githubusercontent.com/7900526/58734950-ca697300-83ad-11e9-8fc0-ec3c01bd20dc.png)
2. Second */registerUser* request with POST
![Screen Shot 2019-05-31 at 1 33 18 PM](https://user-images.githubusercontent.com/7900526/58735005-f553c700-83ad-11e9-8023-209c9c4c771d.png)

This issue is similar to #1710 
/cc @juantoledo @nireeshT @stevegal @jshpopelka272 @tabladrum

Thanks in advance

**Comment by bargemb** [comment]
During signup even if I am getting error that *User already exists*, it doesn't before signup and gets created anyhow.

**Comment by rvema** [comment]
@bargemb Can you verify if your api is active on port 8081 by running a sample request using a rest client like postman?

**Comment by rvema** [comment]
@bargemb did you try the suggestion from @stevegal  in the issue referenced above?
`You may run into quite a lot of cors issues. I work around this by setting up an httpd service to act as a reverse proxy to api and hi so they all have the same server and port. Otherwise the api needs lots of changes to allow cors`

**Comment by bargemb** [comment]
> @bargemb Can you verify if your api is active on port 8081 by running a sample request using a rest client like postman?

@rvema API seems to work as I was successfully able to get **true** response when I hit http://<IP_ADDRESS>:8081/api/ping


> @bargemb did you try the suggestion from @stevegal in the issue referenced above?
> `You may run into quite a lot of cors issues. I work around this by setting up an httpd service to act as a reverse proxy to api and hi so they all have the same server and port. Otherwise the api needs lots of changes to allow cors`

It seems that dockerized version of Hygieia uses NGINX for the same purpose.  I am switching to dockerized installation.

Just wanted to confirm that changing port for API is not a smooth ride

**Comment by rvema** [comment]
@bargemb we have not explored using a port other than 8080 for UI. We will assess the impact and see it can be fixed. Meanwhile if you have the fix for this please contribute back to this project we greatly appreciate it.

**Comment by rvema** [comment]
@bargemb do you have this running on your local machine or on a seperate box? Also I see that you are using ip address is there any reason why you cant use localhost?

**Comment by bargemb** [comment]
I am running this on our internal server.

I have now switched to dockerized setup and default ports are working properly now. Currently it's not blocker issue for me although I would suggest to keep this issue open. 

Nothing specific about the IP address. Would it cause any issues ?

**Comment by stevegal** [comment]
Core policy is quite strict, both port and server must match. I know I had a ton of problems trying to “just” run it all locally... hence setting up an quick reverse proxy using apache, but Nginx works too... and it’s all handled in the docker containers. But there is no magic here... if you want to piece it all together you’ll have to deal with the cors aspect (and rightly so... don’t be tempted to just allow cors... too risky)

**Comment by rvema** [comment]
closing this issue as it was solved.

**Comment by bargemb** [comment]
@rvema the issue with local setup (without using docker and reverse proxy) is not yet solved.

**Comment by stevegal** [comment]
Different browsers have different restrictions on local host cors policy. You could add allow headers in the api, but that could open up a serious misconfiguration attack vector to the casual user. Although I’ve no involvement in this project other than believing this is such an important tool, I don’t think it would be wise to workaround the cors issue out of the box. It’s there to protect the end user.
